[package]
name = "task-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.108"
actix-web = "4.3.1"
sqlx = "0.7.3"
tokio = "1.35.1"
serde = "1.0.193"


[dev-dependencies]
cargo-watch = "8.5.2"
mockall = "0.11.4"
clippy = "0.1.77"

